<?php
/**
 * @file
 * Code for the Core feature.
 */

include_once 'kcore.features.inc';

/**
 * Implements hook_init().
 */
function kcore_init() {
  drupal_add_js(drupal_get_path('module','kcore') . '/js/kcore.js');
  drupal_add_css(drupal_get_path('module','kcore') . '/css/eu_cookies.css', array('group' => CSS_THEME));
  drupal_add_js(array('creaeleadCoeArea' => array('userLoggedIn' => user_is_logged_in())), 'setting');
  drupal_add_js(drupal_get_path('theme', 'crealead') . '/js/crealead_intra_manage_titles.js', array(
    'type' => 'file',
    'group' => JS_THEME,
  ));
}

/**
 * Implements hook_preprocess_html().
 */
function kcore_preprocess_html(&$variables) {
  global $theme;

  if($theme == 'adminimal') {
    // reference my own stylesheet
      drupal_add_css(drupal_get_path('module', 'kcore') . '/css/admin.css', array('weight' => CSS_THEME));
  }
}

/**
 * Implements hook_menu().
 */
function kcore_menu() {
  $items = array();

  $items['admin/config/crealead'] = array(
    'title' => 'Crealead',
    'description' => 'Paramétrage des fonctionnalités Crealead.',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer crealead settings'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/crealead/key_figures'] = array(
    'title' => 'Chiffres clés',
    'description' => 'Réglage des chiffres clés Crealead.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crealead_settings_form'),
    'access arguments' => array('administer crealead settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'kcore.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function kcore_permission() {
  return array(
    'administer crealead settings' => array(
      'title' => t('Administer Crealead settings'),
      'description' => t('Administer various settings for Crealead site.'),
    ),
  );
}

/**
 * Implements hook_menu_alter().
 * Thanks to pfournier, creator of module Empty Front Page (https://www.drupal.org/project/empty_front_page)
 */
function kcore_menu_alter(&$items) {
	$items['node']['page callback'] = 'empty_front_page_callback';
}

function empty_front_page_callback() {
	drupal_set_title('');
	return array();
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function kcore_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  // Shows Referent select field to following roles only : administrateur, webmaster, referent.
  global $user;
  $allowed_roles = array('administrateur','webmaster','référent');
  $user_allowed_roles = array_intersect($allowed_roles, $user->roles);

  if ($user->uid != 1 && empty($user_allowed_roles)) {
	$form['field_user_referent']['#access'] = FALSE;
  }
}

/**
 * Implements hook_email_registration_name().
 */
function kcore_email_registration_name($edit, $account) {
  return $edit['field_user_firstname']['und'][0]['value'] . ' ' . $edit['field_user_lastname']['und'][0]['value'];
}

/**
 * Implements hook_block_info().
 */
function kcore_block_info() {
  $blocks = array();
  $blocks['crealead_coes_number'] = array(
    'info' => t('Crealead : Nombre d\'entrepreneurs'),
  );
  $blocks['crealead_refs_number'] = array(
    'info' => t('Crealead : Nombre de référents'),
  );
  $blocks['crealead_speakers_number'] = array(
    'info' => t('Crealead : Nombre d\'intervenants'),
  );
  $blocks['crealead_meetings_number'] = array(
    'info' => t('Crealead : Nombre de rencontres'),
  );
  $blocks['crealead_sponsors'] = array(
    'info' => t('Crealead : Sponsors'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function kcore_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case 'crealead_coes_number' :
      $coes_number_display = variable_get('coes_number', 1);

      if ($coes_number_display == 1) {
        $number = crealead_users_number('entrepreneur');
      }
      else {
        $number = variable_get('coes_number_value', '100');
      }

      $content = '<div id="coes-number" class="number coes-number">' . $number . '</div>';
      $content .= '<div id="coes-text" class="text coes-text">Co-entrepreneurs <br><span class="under-key-data">et autant de compétences complémentaires</span></div>';
      $block['content'] = $content;
      break;

    case 'crealead_refs_number' :
      $refs_number_display = variable_get('refs_number', 1);

      if ($refs_number_display == 1) {
        $number = crealead_users_number('referent');
      }
      else {
        $number = variable_get('refs_number_value', '100');
      }

      $content = '<div id="refs-number" class="number refs-number">' . $number . '</div>';
      $content .= '<div id="refs-text" class="text refs-text">Membres<br><span class="under-key-data">d’une équipe support pour
accompagner et gérer</span></div>';
      $block['content'] = $content;
      break;

    case 'crealead_speakers_number' :
      $number = variable_get('speakers_number_value', '10');

      $content = '<div id="speakers-number" class="number speakers-number">' . $number . '</div>';
      $content .= '<div id="speakers-text" class="text speakers-text">Intervenants<br><span class="under-key-data">en formations, animations et
prestations.</span></div>';
      $block['content'] = $content;
      break;

    case 'crealead_meetings_number' :
      $number = variable_get('meetings_number_value', '10');

      $content = '<div id="meetings-number" class="number meetings-number">' . $number . '</div>';
      $content .= '<div id="meetings-text" class="text meetings-text">Rencontres par an <br><span  class="under-key-data">organisées pour échanger et
travailler ensemble.</span></div>';
      $block['content'] = $content;
      break;

    case 'crealead_sponsors' :
      $block['subject'] = '';

      $sponsors = array(
        'fond-social-europeen' => array(
          'url' => '',
          //'logo-file' => 'fds-social-europeen_506x130.png',
          'logo-file' => 'fds-social-europeen_506x105_transparent.png'
        ),
        'caisse-epargne' => array(
          'url' => 'https://www.caisse-epargne.fr/languedoc-roussillon/banque-assurance-banque-a-distance.aspx',
          'logo-file' => 'ca-lr_263x57.png'
        ),
        'prefecture' => array(
          'url' => '',
          'logo-file' => 'prefecture_78x100.jpg'
        ),
        'montpellier-metropole' => array(
          'url' => 'http://www.montpellier3m.fr/',
          'logo-file' => 'montpellier-metropole_100x100.png'
        ),
        'cd34' => array(
          'url' => 'http://www.herault.fr/',
          'logo-file' => 'CD34_134x63.png'
        ),
      );

      $path = drupal_get_path('module', 'kcore') . '/sponsors-logos/';
      $content = '<div id="crealead-sponsor">';
      foreach ($sponsors as $name=>$sponsor) {
        $content .= '<span id="' . $name . '">';
        $img = theme('image', array('path' => $path . $sponsor['logo-file']));
        if ($sponsor['url'] != '') {
          $logo = l($img,$sponsor['url'], array('html' => TRUE));
        }
        else {
          $logo = $img;
        }
        $content .= $logo;
        $content .= '</span>';
      }
      $content .= '</div>';
      $block['content'] = $content;
      break;
  }

  return $block;
}

/**
 * Helper functions.
 */

/**
 * Returns the number of active user belonging to role given as paramater.
 * Il no role is passed on, returns the total number of active users.
 *
 * @param $role
 *   A role machine name (ex. Référent role's machine name is 'referent').
 *
 * @return
 *   The number of users.
 */
function crealead_users_number($role=null) {
  $query = db_select('users_roles', 'ur')->fields('ur', array('uid'));
  if (isset($role)) {
    $role = user_role_load_by_name($role);
    $query->condition('ur.rid', $role->rid);
  }
  else {
    $query->distinct();
  }
  $result = $query->execute()->fetchCol();

  return count($result);
}

function kcore_admin_menu_output_alter(&$content) {
  if (isset($content['menu']['admin/index'])) {
    unset($content['menu']['admin/index']);
  }
}

/**
 * Implements hook_node_access().
 */
function kcore_node_access($node, $op, $account) {
  if (isset($node->type) && $node->type == 'webform' && !user_is_logged_in()) {
    return NODE_ACCESS_DENY;
  }
}

/**
 * Implements hook_block_view_alter().
 */
function kcore_block_view_alter(&$data, $block) {
  if ($block->delta == 'menu-coe-area' && !user_is_logged_in()) {
    $data['content'] = array();
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function kcore_form_views_exposed_form_coe_directory_page_alter(&$form, &$form_state, $form_id) {
  dpm('trombi');

}

function kcore_user_cancel_methods_alter(&$methods) {
  $custom_method = array(
    'user_cancel_block_custom_unpublish' => array(
      'title' => 'Désactiver le compte et dépublier son contenu de manière différenciée (option propre au site web Crealead)',
      'description' => 'Le compte est bloqué. Certains contenus restent publiés, d\'autres sont dépubliés, d\'autres encore sont dépubliés de manière conditionnelle.',
    )
  );

  $methods = $custom_method + $methods;
}

/**
 * Implements hook_user_cancel().
 *
 * @param $edit
 * @param $account
 * @param $method
 * @throws \EntityMetadataWrapperException
 */
function kcore_user_cancel($edit, $account, $method) {
    switch ($method) {
        case 'user_cancel_block_custom_unpublish':
            module_load_include('inc', 'node', 'node.admin');

            // - Dépublication des alertes, demandes, événements et offres sans rien faire d'autre
            //
            // - Déplublication des marques, formations, sessions de formation et produit en prévenant par mail les personnes concernées.
            //
            // - Tous les autres types de contenu restent publiés :
            //   actus, articles, brèves, clients, collectifs, comptes-rendus, diapos, dossiers filedepot, flash infos, liens vers documents,
            //   réalisations, événements salle, événements structure, faqs, gazettes, pages de base et réunions d'info.

            $direct_unpublish_types = array(
                'warning',
                'need',
                'event',
                'offer'
            );
            $conditionnal_unpublish_types = array(
                'brand',
                'training',
                'training_session',
                'product'
            );

            $all_unpublish_types = array_merge($direct_unpublish_types, $conditionnal_unpublish_types);

            // Récupération de tous les nodes dont le compte drupal en cours de désactivation est l'auteur.
            $nodes = db_select('node', 'n')
                ->fields('n', array('nid', 'type', 'title'))
                ->condition('uid', $account->uid)
                ->condition('type', $all_unpublish_types, 'IN')
                ->execute()
                //->fetchCol();
                ->fetchAll();
            //dpm($nodes);

            // Tableau pour stocker les emails des personnes à avertir
            $email_data = array(
                'brands' => array(),
                'trainings' => array(),
                'products' => array(),
            );
            // Tableau pour stocker les nid des nodes seuls (voir Dépublication des nodes un peu plus bas dans ce traitement).
            $node_nids = array();

            // Récupération des données (email des coes, nom des marques, intitulés des formations et des produits) à envoyer par email.
            foreach ($nodes as $node) {
                if ($node->type == 'brand') {
                    $brand = entity_metadata_wrapper('node', $node->nid);
                    $brand_name = $brand->title->value();
                    // S'il y a plus d'un coe (le propriétaire de la marque),
                    if (sizeof($brand_coes = $brand->field_brand_coes->value()) > 1) {
                        foreach ($brand_coes as $fci) { // fci = field_collection_item
                            // il faut récupérer l'email des autres coes.
                            if (($coe_id = $fci->field_brand_coe['und'][0]['target_id']) != $account->uid) {
                                $coe = user_load($coe_id);
                                $email_data['brands'][$brand_name][$coe_id] = $coe->mail;
                            }
                        }
                    }
                }
                elseif (($node->type == 'training') || ($node->type == 'product')) {
                    // Il faut récupérer le nid des marques qui ont affiché cette formation ou ce produit partagée.
                    // Cette info est disponible dans la table crealead_shared_content.
                    $brands_displaying_this_shared_content = db_select('crealead_shared_content', 'csc')
                        ->fields('csc', array('brand_id'))
                        ->condition('type', array('training', 'product'), 'IN')
                        ->condition('nid', $node->nid)
                        ->condition('status', 1)
                        ->execute()
                        ->fetchCol();
                    // Puis il faut récupérer les emails des coes de ces marques
                    foreach ($brands_displaying_this_shared_content as $brand_id) {
                        $brand = entity_metadata_wrapper('node', $brand_id);
                        $brand_name = $brand->title->value();
                        $brand_coes = $brand->field_brand_coes->value();
                        foreach ($brand_coes as $fci) { // fci = field_collection_item
                            if (($coe_id = $fci->field_brand_coe['und'][0]['target_id']) != $account->uid) {
                                $coe = user_load($coe_id);
                                $email_data[$node->type . 's'][$node->title][$brand_name][$coe_id] = $coe->mail;
                            }
                        }
                    }

                }
                // A la fin, on en profite pour stocker les nid.
                $node_nids[] = $node->nid;
            }
            //dpm($email_data);

            // Dépublication des nodes
            // Attention, il faut passer en paramètre un tableau de nid seulement, donc $node_nids (voir au dessus).
            node_mass_update($node_nids, array('status' => 0));

            // Envoi des mails
            foreach ($email_data['brands'] as $brand_name => $coe_addresses) {
                foreach ($coe_addresses as $address) {
                    kcore_send_content_unpublication_infos($account, $brand_name, $address, 'brand');
                }
            }

            foreach ($email_data['trainings'] as $training_title => $concerned_brands) {
                foreach ($concerned_brands as $brand_name => $coe_addresses) {
                    foreach ($coe_addresses as $address) {
                        kcore_send_content_unpublication_infos($account, $brand_name, $address, 'training', $training_title);
                    }
                }
            }

            foreach ($email_data['products'] as $product_title => $concerned_brands) {
                foreach ($concerned_brands as $brand_name => $coe_addresses) {
                    foreach ($coe_addresses as $address) {
                        kcore_send_content_unpublication_infos($account, $brand_name, $address, 'product', $product_title);
                    }
                }
            }

            break;
    }
}

/**
 * Send an email to a person concerned by an unpublication type.
 *
 * @param $email_address string Email address of the concerned person.
 * @param $info_type string Unpublication type (brand, training or product).
 */
function kcore_send_content_unpublication_infos($account, $brand_name, $email_address, $info_type, $content_title=null) {

    $to = $email_address;
    $from = "Crealead <contact@crealead.com>";
    $reply_to = "contact@crealead.com";

    $mail_subject = 'Départ de' . $account->name . ' de Crealead - Dépublication de ';

    $mail_body = '<div id="crealead-email-body">' .
        '<br/>' .
        '<p>Bonjour,</p>';

    switch ($info_type) {
        case 'brand':
            dpm('(' . $email_address . ') Suite au départ de ' . $account->name . ', la marque ' . $brand_name . ' a été dépubliée. Si vous souhaitez...');
            $mail_subject .= 'marque.';
            $mail_body .= '<p>Suite au départ de ' . $account->name . ', la marque <b>' . $brand_name . '</b> a été dépubliée.<br/>'
                . 'Si vous souhaitez continuer à l\'afficher sur le site, contactez votre référent.</p>';
            break;

        case 'training':
            dpm('(' . $email_address . ') Suite au départ de ' . $account->name . ', la formation partagée ' . $content_title . ' a été désactivée. Elle n\'est donc plus visible en tant que formation conseillée dans l\'onglet Solutions de la marque ' . $brand_name);
            $mail_subject .= 'formation.';
            $mail_body .='<p>Suite au départ de ' . $account->name . ', la formation partagée <b>' . $content_title . '</b> a été desactivée.<br/>'
            . ' Elle n\'est donc plus visible en tant que formation conseillée dans l\'onglet Solutions de la marque <b>' . $brand_name . '</b></p>';
            break;

        case 'product':
            dpm('(' . $email_address . ') Suite au départ de ' . $account->name . ', le produit partagé ' . $content_title . ' a été désactivé. Il n\'est donc plus visible en tant que produit conseillé dans l\'onglet Solutions de la marque ' . $brand_name);
            $mail_subject .= 'produit.';
            $mail_body .='<p>Suite au départ de ' . $account->name . ', le produit partagé <b>' . $content_title . '</b> a été desactivé.<br/>'
                . ' Il n\'est donc plus visible en tant que produit conseillé dans l\'onglet Solutions de la marque <b>' . $brand_name . '</b></p>';
            break;

    }

    $mail_body .= '</div>';

    $footer_image_fullpath = 'https://www.crealead.com/profiles/crealead/modules/features/kcore/images/bandeau-crealead.jpg';
    $mail_body .=
        '<br/><br/>' .
        '<p class="crealead-email-footer">' .
        '<img src="' . $footer_image_fullpath . '">' .
        '</p>';

    $params = array(
        'headers' => array(
            'Reply-To' => $reply_to,
        ),
        'subject' => $mail_subject,
        'body' => $mail_body,
    );

    if (drupal_mail('kcore', 'unpublished_content_email', $to, language_default(), $params, $from)) {
        $message = t("Unpublished content email sent to %recipient_email.", array('%recipient_email' => $to));
        watchdog('crealead_content_unpublication', $message);
    }
    else {
        $message = t("Unpublished content email sending failed (destinataire: %recipient_email.", array('%recipient_email' => $to));
        watchdog('crealead_content_unpublication', $message);
    }
}

/**
 * Implements hook_mail().
 */
function kcore_mail($key, &$message, $params) {
    switch ($key) {
        case 'unpublished_content_email':
            $message['subject'] = $params['subject'];
            $message['body'][] = $params['body'];
            break;
    }
}