<?php
/**
 * @file
 * Code for the Gazette feature.
 */

include_once 'crealead_gazette.features.inc';

/**
 * Implements hook_views_pre_view().
 */
function crealead_views_pre_render(&$view) {
  //dpm($view);
  if ($view->name == "gazettes" && $view->current_display == 'page_gazettes'){
    if (!user_is_logged_in()) {
      unset($view->result);
      $view->header['area']->options['content'] =
        "<h3>Vous n'êtes pas autorisé à visualiser cette page. Merci de vous identifier.</h3>";
    }

  }
}

/**
 * Implements hook_node_view().
 */
function crealead_gazette_node_view($node, $view_mode, $langcode) {
  //dpm($node);
  if ($node->type == "gazette") {
    if (!user_is_logged_in()) {
      $node->content['body'][0]['#markup'] =
        "<h3>Vous n'êtes pas autorisé à visualiser cette page. Merci de vous identifier.</h3>";
    }
  }
}
