<?php
/**
 * @file
 * Code for the Espace associés feature.
 */

include_once 'crealead_associates.features.inc';

/**
 * Implements hook_menu().
 */
function crealead_associates_menu() {
    $items['admin/config/crealead/associates'] = array(
        'title' => 'Espace associés',
        'description' => 'Paramétrage de la page Espace associés (espace coes).',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('crealead_associates_settings_form'),
        'access arguments' => array('administer crealead settings'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'crealead_associates.admin.inc',
    );

    return $items;
}

/**
 * Implements hook_views_pre_view().
 */
function crealead_associates_views_pre_view(&$view, &$display_id, &$args) {
    if ($view->name == 'needs' && $view->current_display == 'ass_links_list') { // Bloc Liens vers docs associés de la vue Demandes.
        drupal_add_css(drupal_get_path('module', 'crealead_associates') . '/css/crealead_associates.css');
    }
}

function crealead_associates_init() {
//    dpm(current_path());
    if (user_is_logged_in() && 'espace-co-entrepreneur/breves' == current_path()) {
        global $user;

        if (crealead_associates_is_current_user_external_associate($user)) {
            drupal_goto('espace-co-entrepreneur/espace-associes');
        }
    }
}

function crealead_associates_is_current_user_external_associate($user) {
    if (count($user->roles) == 2 && in_array('associé', $user->roles)) {
        return true;
    }
    return false;
}
