<?php
/**
 * @file
 * Code for the Actualités feature.
 */

include_once 'crealead_news.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function crealead_news_form_news_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_sorting_date']['#disabled'] = TRUE;
  $form['#groups']['group_crealead_settings']->weight = 1000;
}

/**
 * Implements hook_node_presave().
 */
function crealead_news_node_presave($node) {
  if ($node->type == 'news') {
    if (!empty($node->field_news_date['und'])) {
      $node->field_sorting_date['und'][0]['value'] = $node->field_news_date['und'][0]['value'];
    }
    else {
      $node->field_sorting_date['und'][0]['value'] = $node->created;
    }
  }
}