<?php
/**
 * @file
 * Code for the Articles feature.
 */

include_once 'crealead_articles.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function crealead_articles_form_article_node_form_alter(&$form, &$form_state, $form_id) {
  // If user is not allowed, field_news_kind and field_related_themes removed.
  global $user;
  $current_user_roles = $user->roles;
  $crealead_news_allowed_roles = array('administrateur','webmaster','référent');
  $current_user_allowed_roles = array_intersect($crealead_news_allowed_roles, $current_user_roles);
  if (empty($current_user_allowed_roles) & $user->uid != 1) {
    $form['field_article_kind']['#access'] = FALSE;
    //$form['field_landing_pages']['#access'] = FALSE;
  }

  // Related brands list handling ----------------------------------------------
  // The article create/edit form always contains a user id.
  // If article is being created, user id is the current user id.
  // If article is being modified, user id is the news author id.
  // In either cases, we must seek for brands the concerned user belongs to.
  $query = db_select('field_data_field_brand_coe', 'coe');
  $query->fields('coe', array('entity_id', 'field_brand_coe_target_id'));
  $query->join('field_data_field_brand_coes', 'coes', 'coes.field_brand_coes_value=coe.entity_id');
  $query->fields('coes', array('entity_id'));
  $query->condition('field_brand_coe_target_id', $form['uid']['#value']);
  $news_brands = $query->execute()->fetchAllKeyed(2, 2);
  
  $brand_options = $form['field_article_related_brands']['und']['#options'];
  foreach ($brand_options as $key => $brand) {
    if (!in_array($key, $news_brands)) {
      unset($brand_options[$key]);
    }
  }
  $form['field_article_related_brands']['und']['#options'] = $brand_options;

  // Then, if news is being modified and current user is not news author,
  // we must display a disabled brand list, unless current used is allowed to.
  if (isset($form['nid']['#value']) && $user->uid != $form['uid']['#value'] && empty($current_user_allowed_roles) & $user->uid != 1) {
    $form['field_article_related_brands']['#disabled'] = TRUE;
  }

  // If article is being created from a brand page,
  // we must catch the brand nid from url
  // and check the corresponding brand in field_related_brands field.
  if (!isset($form['nid']['#value']) && NULL != arg(3)) {
    $form['field_article_related_brands']['und']['#default_value'] = array(arg(3));
  }
  // End of Related brands list handling ---------------------------------------

  // Hugly hack to remove no longer wanted field_article_kind options
  // (Cannot be deleted because already used).
  unset($form['field_article_kind']['und']['#options'][2]);
  unset($form['field_article_kind']['und']['#options'][3]);

  // We must display only sector brands the parent brand(s) of the current article is (are) related to.
  // First, we get the parent brands.
  $parent_brands = crealead_articles_get_parent_brands($form['nid']['#value']);

  // If any parent brands exist, we get the sector brands of each parent brand.
  if (!empty($parent_brands)) {
    $parent_sector_brands = crealead_brands_get_parent_sector_brands($parent_brands);

    // If any parent sector brands exist
    if (!empty($parent_sector_brands)) {
      // We have to clean the sector brand field options array by keeping only the parent sector brands.
      $form['field_related_sector_brands']['und']['#options'] =
        crealead_clean_sector_brands_options($form['field_related_sector_brands']['und']['#options'], $parent_sector_brands);
    }
    // otherwise we remove the related sector brands field from display.
    else {
      $form['field_related_sector_brands']['#access'] = FALSE;
    }
  }
  // otherwise we remove the related sector brands field from display.
  else {
    $form['field_related_sector_brands']['#access'] = FALSE;
  }
}

function crealead_articles_get_parent_brands($article_id) {
  if (!isset($article_id)) return array();

  $query = db_select('field_data_field_article_related_brands', 'farb');
  $query->fields('farb', array('field_article_related_brands_target_id'));
  $query->condition('entity_id', $article_id);

  return $query->execute()->fetchAllKeyed(0,0);
}

/**
 * Implements hook_views_pre_render().
 */
function crealead_articles_views_pre_render(&$view) {
  if ($view->name == 'articles' && $view->current_display == 'brand_articles') {
    // Link 'Ajouter un article' must be added to block only for coes attached to the current brand.
    $current_brand = $view->current_entity;
    $wrapper = entity_metadata_wrapper('node', $current_brand);
    $brand_coes = $wrapper->field_brand_coes->value();

    global $user;
    foreach ($brand_coes as $brand_coe) {
      if ($user->uid != $brand_coe->field_brand_coe['und'][0]['target_id']) {
        continue;
      }
      else {
        $view->footer['area']->options['content'] = l(
          'Ajouter un article',
          '/node/add/article/' . $current_brand->nid,
          array('query' => array('destination' => current_path()))
        );
        break;
      }
    }
  }
}
