<?php
/**
 * @file
 * Code for the Articles feature.
 */

include_once 'crealead_articles.features.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function crealead_articles_form_article_node_form_alter(&$form, &$form_state, $form_id) {

  // If user is not allowed, field_news_kind and field_related_themes removed.
  global $user;
  $current_user_roles = $user->roles;
  $crealead_news_allowed_roles = array('administrateur','webmaster','référent');
  $current_user_allowed_roles = array_intersect($crealead_news_allowed_roles, $current_user_roles);
  if (empty($current_user_allowed_roles) & $user->uid != 1) {
    $form['field_article_kind']['#access'] = FALSE;
    $form['field_landing_pages']['#access'] = FALSE;
  }
}