<?php
/**
 * @file
 * Code for the Produits feature.
 */

include_once 'crealead_products.features.inc';

function crealead_products_form_product_node_form_alter(&$form, &$form_state, $form_id) {
  drupal_add_js(drupal_get_path('module','crealead_products') . '/js/crealead_products.js');
  global $user;
  $current_user_roles = $user->roles;
  $crealead_products_allowed_roles = array('administrateur','webmaster','référent');
  $current_user_allowed_roles = array_intersect($crealead_products_allowed_roles, $current_user_roles);

  // Related brands list handling ----------------------------------------------
  // The product create/edit form always contains a user id.
  // If product is being created, user id is the current user id.
  // If product is being modified, user id is the product author id.
  // In either cases, we must seek for brands the concerned user belongs to.
  $query = db_select('field_data_field_brand_coe', 'coe');
  $query->fields('coe', array('entity_id', 'field_brand_coe_target_id'));
  $query->join('field_data_field_brand_coes', 'coes', 'coes.field_brand_coes_value=coe.entity_id');
  $query->fields('coes', array('entity_id'));
  $query->condition('field_brand_coe_target_id', $form['uid']['#value']);
  $product_brands = $query->execute()->fetchAllKeyed(2, 2);

  $brand_options = $form['field_product_related_brands']['und']['#options'];
  foreach ($brand_options as $key => $brand) {
    if (!in_array($key, $product_brands)) {
      unset($brand_options[$key]);
    }
  }

  $form['field_product_related_brands']['und']['#options'] = $brand_options;

    // Then, if product is being modified and current user is not news author,
    // we must display a disabled brand list, unless current used is allowed to.
    /*if (isset($form['nid']['#value']) && $user->uid != $form['uid']['#value'] && empty($current_user_allowed_roles) & $user->uid != 1) {
      $form['field_product_related_brands']['#disabled'] = TRUE;
    }*/
    // End of Related brands list handling ---------------------------------------

    // If product is being created from a brand page,
    // we must catch the brand nid from url
    // and check the corresponding brand in field_related_brands field.
    if (!isset($form['nid']['#value']) && NULL != arg(3)) {
      $form['field_product_related_brands']['und']['#default_value'] = arg(3);
    }
    // End of Related brands list handling ---------------------------------------

  // We must display only sector brands the parent brand(s) of the current product is (are) related to.
  // First, we get the parent brands.
  $parent_brands = crealead_products_get_parent_brands($form['nid']['#value']);

  // If any parent brands exist, we get the sector brands of each parent brand.
  if (!empty($parent_brands)) {
    $parent_sector_brands = crealead_brands_get_parent_sector_brands($parent_brands);

    // If any parent sector brands exist
    if (!empty($parent_sector_brands)) {
      // We have to clean the sector brand field options array by keeping only the parent sector brands.
      $form['field_related_sector_brands']['und']['#options'] =
        crealead_clean_sector_brands_options($form['field_related_sector_brands']['und']['#options'], $parent_sector_brands);
    }
    // otherwise we remove the related sector brands field from display.
    else {
      $form['field_related_sector_brands']['#access'] = FALSE;
    }
  }
  // otherwise we remove the related sector brands field from display.
  else {
    $form['field_related_sector_brands']['#access'] = FALSE;
  }

  // Handling of field_is_structure display
  $allowed_roles = array('administrateur','webmaster','assistant','direction','entrepreneur prestataire','pôle gestion','référent');
  if (empty(array_intersect($allowed_roles, $current_user_roles))) {
    $form['field_is_structure']['#access'] = FALSE;
  }

    // GESTION DU CHAMP TECHNIQUE DE RECHERCHE
    // 1 - Déplacement de l'onglet vertical "Champs Crealed" vers la dernière position.
    $form['#groups']['group_crealead_fields']->weight = 200;
    // 2 - Champ en lecture seule
    $form['field_product_search']['und'][0]['value']['#attributes']['readonly'] = 'readonly';
}


function crealead_products_get_parent_brands($product_id) {
  if (!isset($product_id)) return array();

  $query = db_select('field_data_field_product_related_brands', 'fprb');
  $query->fields('fprb', array('field_product_related_brands_target_id'));
  $query->condition('entity_id', $product_id);

  return $query->execute()->fetchAllKeyed(0,0);
}

/**
 * Implements hook_views_pre_render().
 */
function crealead_products_views_pre_render(&$view) {
  if ($view->name == 'products' && $view->current_display == 'entity_view_1') {
    // Link 'Ajouter un produit' must be added to block only for coes attached to the current brand.
    if (isset($view->current_entity)) {
      $current_brand = $view->current_entity;
    }
    else {
      $current_brand = node_load(arg(1));
    }
    $wrapper = entity_metadata_wrapper('node', $current_brand);
    $brand_coes = $wrapper->field_brand_coes->value();
    global $user;
    foreach ($brand_coes as $brand_coe) {
      if (!empty($brand_coe->field_brand_coe) && $user->uid != $brand_coe->field_brand_coe['und'][0]['target_id']) {
        continue;
      }
      else {
        $view->header['area']->options['content'] = l(
          'Ajouter un produit',
          '/node/add/product/' . $current_brand->nid,
          array('query' => array('destination' => current_path() . '#bootstrap-fieldgroup-nav-item--solutions'))
        );
        break;
      }
    }
    /*


    global $user;
    foreach ($brand_coes as $brand_coe) {
      if ($user->uid != $brand_coe->field_brand_coe['und'][0]['target_id']) {
        continue;
      }
      else {
        $view->header['area']->options['content'] = l(
          'Ajouter un produit',
          '/node/add/produit/' . $current_brand->nid,
          array('query' => array('destination' => current_path()))
        );
        break;
      }
    }*/

  }
  elseif ($view->name == 'products' && $view->current_display == 'allowed_products') {
    // If referer is the ajax call, brand_nid can be found as argument 4, otherwise
    if(arg(4)) {
      $query = db_select('node', 'n')->fields('n', array('title'));
      $query->condition('n.nid', arg(4));
      $brand_name = $query->execute()->fetchField();
    }
    else {
      $brand_name = $view->current_entity->title;
    }

    $view->build_info['title'] = str_replace('brand_name', $brand_name, $view->build_info['title']);
  }
}

/**
 * Implements hook_node_presave().
 */
function crealead_products_node_presave($node) {
  if ($node->type == 'product') {
    $product_name = $node->title . ' ';
    $product_intro = $product_earnings = $product_description = $product_who = $product_brands = '';

    if (isset($node->field_introduction['und'][0]['value'])) {
        $product_intro = strip_tags($node->field_introduction['und'][0]['value']) . ' ';
    }
    if (isset($node->field_product_earnings['und'][0]['value'])) {
        $product_earnings = strip_tags($node->field_product_earnings['und'][0]['value']) . ' ';
    }
    if (isset($node->body['und'][0]['value'])) {
        $product_description = strip_tags($node->body['und'][0]['value']) . ' ';
    }
    if (isset($node->field_product_to_whom['und'][0]['value'])) {
        $product_who = strip_tags($node->field_product_to_whom['und'][0]['value']) . ' ';
    }

    if (!empty($node->field_product_related_brands['und'])) {
        foreach ($node->field_product_related_brands['und'] as $brand) {
            $query = db_select('node', 'n');
            $query->fields('n', array('title'))
                ->condition('n.nid', $brand['target_id']);
            $result = $query->execute()->fetchField();
            $product_brands .= $result;
        }
    }

    $search_data = $product_name
        . $product_intro
        . $product_earnings
        . $product_description
        . $product_brands;
    $search_array = array('value' => $search_data, 'format' => 'plain_text');

    if (!isset($node->field_product_search['und'][0])) {
        $node->field_product_search['und'][] = $search_array;
    }
    else {
        $node->field_product_search['und'][0] = $search_array;
    }
  }
}

function crealead_products_fill_search_field() {
    $query = new EntityFieldQueryExtraFields();
    $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'product')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->addExtraField('', 'title', 'title', 'node');
    $result = $query->execute();

    $count = 0;
    if (isset($result['node'])) {
        $products = node_load_multiple(array_keys($result['node']));
        foreach ($products as $product) {
            node_save($product);
            $count++;
        }
    }
    dpm($count . ' nodes de type product enregistrés');
}

