<?php
/**
 * @file
 * crealead_profiles.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function crealead_profiles_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'drupal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '044bad16-aba0-4200-be41-b6cfc8a07d7a',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'logiciels libres',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e5e5f82-ccbc-4b7f-b8e2-3e9c8f48cdc7',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Commerçants et artisans',
    'description' => '',
    'format' => 'full_html',
    'weight' => 6,
    'uuid' => '22c4b38c-0df9-4697-8f56-1c7171ad86d6',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'drupal',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28e2fe17-21e1-4a78-8bd2-ddce30731ab9',
    'vocabulary_machine_name' => 'entrepreneur_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Consultants formateurs',
    'description' => '<p>Qu\'est-ce que CreaExpert ?<br />
<br />
Les Experts sont les entrepreneurs de Crealead exerçant une activité de prestation intellectuelle au service des entreprises.</p>

<p>Consultants, Formateurs, Coachs, Prestataires avec différents modes d\'intervention, nous partageons nos meilleures pratiques pour faire progresser la qualité de nos prestations.</p>

<p>&nbsp;</p>
',
    'format' => 'full_html',
    'weight' => 3,
    'uuid' => '2a16e571-35dc-4854-8ccf-4037d23c11b5',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'bureautique',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2bc35ad5-cce6-4892-8d8b-f85d052da35b',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'electricité photo-voltaïque',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d192367-5437-4c72-8138-1c3f498a258b',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'php',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2f1c60f0-4392-4bb9-97ff-1ddf5cea1192',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Technologies de l\'information et de la communication',
    'description' => '<p>Les métiers "T.I.C." : Techniologies de l\'Information et de la Communication,regroupent :&nbsp;"les techniques principalement de l\'informatique, de l\'audiovisuel, des multimédias, de l\'Internet et des télécommunications qui permettent aux utilisateurs de communiquer, d\'accéder aux sources d\'information, de stocker, de manipuler, de produire et de transmettre l\'information sous toutes les formes: texte, document, musique, son, image, vidéo, et interface graphique interactive". (Wikipedia)</p>
',
    'format' => 'full_html',
    'weight' => 4,
    'uuid' => '4bcbd360-8cac-4b48-b156-99bc51cdeecb',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'electricité',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4d7b1d6b-9f1e-415e-a43e-67a892173151',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'git',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ebe72f3-f36f-4beb-a9ac-1431ff1c4c25',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Communication',
    'description' => '<p>Dans cette section vous trouverez les créatifs qui vous permettent de mettre sur des supports (virtuels ou physiques) votre image de marque : Flyers, cartes de visite, dépliants, affiches, mais encore, sites Internet, chartes graphiques, etc.</p>
',
    'format' => 'full_html',
    'weight' => 2,
    'uuid' => '968c624e-18fa-42dd-8fa0-b8c1336bfec2',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Agriculture et environnement',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '9bd98d14-1229-4def-b367-f937ac900e73',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Service aux particuliers',
    'description' => '',
    'format' => 'full_html',
    'weight' => 5,
    'uuid' => 'b8a926d4-c201-4e69-8648-ab19de4886f6',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'photo-voltaïque',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cad8a8c8-6172-4995-95c0-1aa7e8706e92',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'drupal cms',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cf4623cc-8e1b-453b-8f3c-5c6b463dc846',
    'vocabulary_machine_name' => 'entrepreneur_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'cms',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e189eade-3947-4179-9b0b-8977ebe176dd',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'photovoltaïque',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef952b28-2cea-4e54-9bd3-f55938c694f3',
    'vocabulary_machine_name' => 'entrepreneur_tags',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'web',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f10e6a3b-b13c-4c5d-a2eb-a23de248a740',
    'vocabulary_machine_name' => 'competencies',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Bâtiment',
    'description' => '',
    'format' => 'full_html',
    'weight' => 1,
    'uuid' => 'ff0742c7-b826-4473-b08e-69b6d6e785f4',
    'vocabulary_machine_name' => 'business_sectors',
    'metatags' => array(),
  );
  return $terms;
}
